### ISSUE TITLE
license compatibility problems (gpl linked with openssl)

### ISSUE THREAD

**Issue by samueloph** [joswr1ght/cowpatty#1]
Hello Joshua,

I really wanted to see cowpatty as part of the debian distribution, i'm working together with some people from Kali linux towards packaging their tools on debian (and thus let Kali sync the package from debian, making the package more stable and secure).

cowpatty is one of the packages i'm working on right now, but i have found problems which makes impossible to ship cowpatty on debian with openssl linked. You see, the GPL license is incompatible with openssl, more info here[0][1][2].

I'm asking you to consider adding the OpenSSL exemption on your license definition, as suggested on [2]:
```
 * In addition, as a special exception, the copyright holders give
 * permission to link the code of portions of this program with the
 * OpenSSL library under certain conditions as described in each
 * individual source file, and distribute linked combinations
 * including the two.
 * You must obey the GNU General Public License in all respects
 * for all of the code used other than OpenSSL.  If you modify
 * file(s) with this exception, you may extend this exception to your
 * version of the file(s), but you are not obligated to do so.  If you
 * do not wish to do so, delete this exception statement from your
 * version.  If you delete this exception statement from all source
 * files in the program, then also delete it here.
```

This would allow us to package cowpatty for debian (and note that all derivatives would get the package too). If you're willing to, i suggest doing the changes and making a new release, that would make things easier for me, but just committing the changes is enough for me, i can package a specific git commit instead of a release on Debian.

PS.: It would be also possible to patch cowpatty to use another lib that is compatible with GPL, but the easiest and quickest way is to add the license exemption.

Thanks for your consideration, i'm sending you an email just to make sure you see this issue.

[0]https://people.gnome.org/~markmc/openssl-and-the-gpl.html
[1]https://lists.debian.org/debian-legal/2002/10/msg00113.html
[2]https://lists.debian.org/debian-legal/2004/05/msg00595.html

**Comment by joswr1ght** [comment]
I've actually become more agreeable with a 3-clause BSD license:

```
Copyright (c) 2018, Joshua Wright <jwright@willhackforsushi.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification,
are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright 
notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above 
copyright
        notice, this list of conditions and the following disclaimer in 
the
        documentation and/or other materials provided with the 
distribution.

     3. Neither the names of the above authors nor the names of 
contributors
        may be used to endorse or promote products derived from this 
software
        without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS "AS 
IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED 
AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF 
THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Will that be suitable as an alternative to modifying the GPL to permit 
OpenSSL use?

Thanks,

-Josh

**Comment by samueloph** [comment]
@joswr1ght I'm not aware of any incompatibility between BSD-3-clause and openssl, please go ahead.

Thanks

**Comment by samueloph** [comment]
@joswr1ght thank, i'll probably have to create a simple manpage for cowpatty for the debian package, would you be willing to make a new release with the license change + manpage? That would make thinks easier and would also get the attention of the not Debian derivative distros like Gentoo and Arch linux*, so they would package the last version.

* They will probably notice through https://repology.org/metapackage/cowpatty/versions that there's a new release packaged on other distros.

**Comment by joswr1ght** [comment]
If you want to submit a PR with a man page I'll gladly include it and 
make a release.

Thanks!

-Josh
