### ISSUE TITLE
cowpatty install link is not working

### ISSUE THREAD

**Issue by micahkane** [joswr1ght/cowpatty#11]
E: Failed to fetch http://http.kali.org/kali/pool/main/c/cowpatty/cowpatty_4.8-2_i386.deb  404  Not Found [IP: 18.211.24.19 80]
i keep getting the following error when trying to install

**Comment by joswr1ght** [comment]
This isn't an issue with Cowpatty, it's something to do with the Kali package maintainers. Also, I'd recommend using Aircrack-ng these days, no need to use Cowpatty anymore when Aircrack-ng has done such amazing work. Thanks!
